language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q fakeroot fakechroot cowdancer
  - sudo cp travis/lsb-release /etc/lsb-release

install:
  - pip install -r requirements.txt

script: nose2
